services:
  web:
    build: .
    container_name: bulk-sender-web
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: ['npm', 'run', 'dev']
    volumes:
      - .:/app
      - /app/node_modules
